"""The single interface used by every UI page."""

from __future__ import annotations

from typing import Protocol

from ..models import AccessRecord, ConsentRecord, TransactionResult


class PlatformGateway(Protocol):
    def accounts(self) -> list[str]: ...
    def account_label(self, account: str) -> str: ...
    def network_name(self) -> str: ...
    def is_registered(self, account: str) -> bool: ...
    def identity_hash(self, account: str) -> str | None: ...
    def register_identity(self, account: str, identity_hash: str) -> TransactionResult: ...
    def add_credential(self, account: str, credential_hash: str) -> TransactionResult: ...
    def credential_hashes(self, account: str) -> list[str]: ...
    def grant_consent(
        self, owner: str, requester: str, credential_hash: str, duration_days: int
    ) -> TransactionResult: ...
    def owner_consents(self, owner: str) -> list[ConsentRecord]: ...
    def revoke_consent(self, owner: str, consent_id: int) -> TransactionResult: ...
    def access_data(self, requester: str, owner: str, credential_hash: str) -> AccessRecord: ...
    def access_records(self, owner: str | None = None) -> list[AccessRecord]: ...
    def reward_balance(self, account: str) -> float: ...
    def reward_symbol(self) -> str: ...

